language: java
jdk:
  - oraclejdk12
  - openjdk12
  
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
  - curl -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_IP}${SFTP_DIR}
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
