language: java
jdk:
  - oraclejdk12
  - openjdk12
  
addons:
  apt:
    packages:
      - sshpass
  
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
  
  - ls
  - export SSHPASS=$SFTP_PASSWORD
  - sshpass -e scp Hadder-Build.jar $SFTP_USER@$SFTP_IP:$SFTP_DIR
  - sshpass -e ssh $SFTP_USER@$SFTP_IP $SFTP_DIR/deploy.sh
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
