base_url: 'https://bigbotnetwork.com'
commit_message: '[ci skip] New %language% translation'
files:
  - source: /src/main/Translations/en_us.properties
    translation: /src/main/Translations/%two_letters_code%/%original_file_name%
